name = "ReachabilityBase"
uuid = "379f33d0-9447-4353-bd03-d664070e549f"
version = "0.3.3"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ExprTools = "0.1"
InteractiveUtils = "<0.0.1, 1.2"
LinearAlgebra = "<0.0.1, 1.2"
Random = "<0.0.1, 1.2"
Requires = "0.5, 1"
SparseArrays = "<0.0.1, 1.2"
StaticArrays = "1"
julia = "1.2"

[extensions]
StaticArraysExt = "StaticArrays"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
